### PR TITLE
added an example for the kmc branch which uses n2p2

### PR DESCRIPTION
**Pull request by glensk**

### CODE REVIEW

**Comment by venkatkapil24** [comment]
That's very useful Albert. May I suggest you to use the same naming format that we have used for the rest of the examples ? Like input.xml for the i-pi input, in.lmp data.lmp init.xyz etc.

**Comment by glensk** [comment]
sure, let me change that

**Comment by glensk** [comment]
is that ok?

**Comment by ceriottm** [comment]
@glensk I merged in a change I made to geop, now you can set a conv_exit flag to False so it doesn't exit when converged. pls use this mechanism rather than hardcoding convergence settings

**Pull request merged**
